application:
  port: 8081
  base_url: "http://127.0.0.1"
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "postgres"
  db_name: "postgres"
email_client:
  base_url: localhost
  sender_email: 19081010016@student.upnjatim.ac.id
  authorization_token: POSTMARK_API_TEST
  timeout_milliseconds: 3000
redis_uri: "redis://redis:6379"
