application:
  port: 8081
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  db_name: "newsletter"
email_client:
  base_url: localhost
  sender_email: 19081010016@student.upnjatim.ac.id
  authorization_token: POSTMARK_API_TEST
  timeout_milliseconds: 3000
